### ISSUE TITLE
New Plugin -- CTFd Whale

### ISSUE THREAD

**Issue by glzjin** [CTFd/plugins#21]
https://github.com/glzjin/CTFd-Whale

A plugin for CTFd which allow your users to launch a standalone instance for challenges.

![https://www.zhaoj.in/wp-content/uploads/2019/08/1565947849bb2f3ed7912fb85afbbf3e6135cb89ca.png](https://www.zhaoj.in/wp-content/uploads/2019/08/1565947849bb2f3ed7912fb85afbbf3e6135cb89ca.png)

![https://www.zhaoj.in/wp-content/uploads/2019/08/15659478989e90e7a3437b1bdd5b9e617d7071a79f.png](https://www.zhaoj.in/wp-content/uploads/2019/08/15659478989e90e7a3437b1bdd5b9e617d7071a79f.png)

![https://www.zhaoj.in/wp-content/uploads/2019/08/1565923903609e6c236759a5663be8e0fb57904482.png](https://www.zhaoj.in/wp-content/uploads/2019/08/1565923903609e6c236759a5663be8e0fb57904482.png)

**Comment by ColdHeat** [comment]
Please provide as a PR to a submodule to the plugin.
